version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=url_shortener
      - DB_PORT=5432
      - JWT_SECRET_KEY=your_secret_key
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=url_shortener
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    restart: unless-stopped

volumes:
  postgres_data: